2020-04-23 16:14:24,901 ERROR: Exception on / [GET] [in /Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/wongchiuching/Downloads/microblog-1/app/main/routes.py", line 40, in index
    prev_url=prev_url)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/wongchiuching/Downloads/microblog-1/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/wongchiuching/Downloads/microblog-1/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/Users/wongchiuching/Downloads/microblog-1/app/templates/base.html", line 101, in block "navbar"
    <a class="dropdown-item" href="{{ url_for('auth.edit_bill') }}">{{ _('Bill') }}</a>
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.edit_bill'. Did you forget to specify values ['bill_id']?
2020-04-23 16:15:31,554 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-23 16:15:32,770 ERROR: Exception on / [GET] [in /Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/wongchiuching/Downloads/microblog-1/app/main/routes.py", line 40, in index
    prev_url=prev_url)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/wongchiuching/Downloads/microblog-1/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/wongchiuching/Downloads/microblog-1/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/Users/wongchiuching/Downloads/microblog-1/app/templates/base.html", line 101, in block "navbar"
    <a class="dropdown-item" href="{{ url_for('auth.edit_bill') }}">{{ _('Bill') }}</a>
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/wongchiuching/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.edit_bill'. Did you forget to specify values ['bill_id']?
2020-04-23 16:21:49,809 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-23 16:30:31,005 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-24 00:28:28,977 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-24 01:27:01,821 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-24 01:38:18,348 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-24 01:38:30,573 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-24 02:08:49,359 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-26 16:14:59,501 INFO: Microblog startup [in /Users/wongchiuching/Downloads/microblog-1/app/__init__.py:74]
2020-04-30 15:40:30,549 INFO: Microblog startup [in C:\Users\NineHo\PycharmProjects\HKBN-PROJECT\app\__init__.py:74]
2020-04-30 15:48:30,270 INFO: Microblog startup [in C:\Users\NineHo\PycharmProjects\HKBN-PROJECT\app\__init__.py:74]
2020-04-30 16:05:24,045 INFO: Microblog startup [in C:\Users\NineHo\PycharmProjects\HKBN-PROJECT\app\__init__.py:74]
2020-04-30 17:00:26,803 INFO: Microblog startup [in C:\Users\NineHo\PycharmProjects\HKBN-PROJECT\app\__init__.py:74]
2020-04-30 17:06:35,825 INFO: Microblog startup [in C:\Users\NineHo\PycharmProjects\HKBN-PROJECT\app\__init__.py:74]
2020-04-30 17:07:45,992 INFO: Microblog startup [in C:\Users\NineHo\PycharmProjects\HKBN-PROJECT\app\__init__.py:74]
